import { KnownDevices } from "puppeteer";

export const iphoneDevices = [
  KnownDevices["iPhone 4"],
  KnownDevices["iPhone 5"],
  KnownDevices["iPhone 6"],
  KnownDevices["iPhone 6 Plus"],
  KnownDevices["iPhone 7"],
  KnownDevices["iPhone 7 Plus"],
  KnownDevices["iPhone 8"],
  KnownDevices["iPhone 8 Plus"],
  KnownDevices["iPhone SE"],
  KnownDevices["iPhone X"],
  KnownDevices["iPhone XR"],
  KnownDevices["iPhone XS"],
  KnownDevices["iPhone XS Max"],
  KnownDevices["iPhone 11"],
  KnownDevices["iPhone 11 Pro"],
  KnownDevices["iPhone 11 Pro Max"],
  KnownDevices["iPhone 12"],
  KnownDevices["iPhone 12 Mini"],
  KnownDevices["iPhone 12 Pro"],
  KnownDevices["iPhone 12 Pro Max"],
  KnownDevices["iPhone 13"],
  KnownDevices["iPhone 13 Mini"],
  KnownDevices["iPhone 13 Pro"],
  KnownDevices["iPhone 13 Pro Max"],
  KnownDevices["iPhone 14"],
  KnownDevices["iPhone 14 Plus"],
  KnownDevices["iPhone 14 Pro"],
  KnownDevices["iPhone 14 Pro Max"],
  KnownDevices["iPhone 15"],
  KnownDevices["iPhone 15 Plus"],
  KnownDevices["iPhone 15 Pro"],
  KnownDevices["iPhone 15 Pro Max"],
];

export const ipadDevices = [
  KnownDevices["iPad"],
  KnownDevices["iPad 2"],
  KnownDevices["iPad Mini"],
  KnownDevices["iPad Mini 2"],
  KnownDevices["iPad Mini 3"],
  KnownDevices["iPad Mini 4"],
  KnownDevices["iPad Air"],
  KnownDevices["iPad Air 2"],
  KnownDevices["iPad Pro (9.7-inch)"],
  KnownDevices["iPad Pro (10.5-inch)"],
  KnownDevices["iPad Pro (11-inch)"],
  KnownDevices["iPad Pro (12.9-inch)"],
  KnownDevices["iPad (5th generation)"],
  KnownDevices["iPad (6th generation)"],
  KnownDevices["iPad (7th generation)"],
  KnownDevices["iPad (8th generation)"],
  KnownDevices["iPad (9th generation)"],
  KnownDevices["iPad (10th generation)"],
  KnownDevices["iPad Air (3rd generation)"],
  KnownDevices["iPad Air (4th generation)"],
  KnownDevices["iPad Air (5th generation)"],
  KnownDevices["iPad Mini (5th generation)"],
  KnownDevices["iPad Mini (6th generation)"],
  KnownDevices["iPad Pro (11-inch, 2nd generation)"],
  KnownDevices["iPad Pro (11-inch, 3rd generation)"],
  KnownDevices["iPad Pro (12.9-inch, 2nd generation)"],
  KnownDevices["iPad Pro (12.9-inch, 3rd generation)"],
  KnownDevices["iPad Pro (12.9-inch, 4th generation)"],
  KnownDevices["iPad Pro (12.9-inch, 5th generation)"],
];

export const androidDevices = [
  KnownDevices["Galaxy Note 3"],
  KnownDevices["Galaxy Note II"],
  KnownDevices["Galaxy S III"],
  KnownDevices["Galaxy S5"],
  KnownDevices["Galaxy S7"],
  KnownDevices["Galaxy S8"],
  KnownDevices["Nokia N9"],
  KnownDevices["Galaxy S9+"],
  KnownDevices["Nexus 10"],
  KnownDevices["Nexus 4"],
  KnownDevices["Nexus 5"],
  KnownDevices["Nexus 6"],
  KnownDevices["Nexus 7"],
  KnownDevices["Pixel 2"],
  KnownDevices["Pixel 3"],
  KnownDevices["Pixel 4"],
  KnownDevices["Pixel 5"],
];

export const androidTablets = [
  KnownDevices["Samsung Galaxy Tab S3"],
  KnownDevices["Samsung Galaxy Tab S4"],
  KnownDevices["Samsung Galaxy Tab S5e"],
  KnownDevices["Samsung Galaxy Tab S6"],
  KnownDevices["Samsung Galaxy Tab S6 Lite"],
  KnownDevices["Samsung Galaxy Tab S7"],
  KnownDevices["Samsung Galaxy Tab S7 Plus"],
  KnownDevices["Samsung Galaxy Tab S8"],
  KnownDevices["Samsung Galaxy Tab S8 Plus"],
  KnownDevices["Google Pixel C"],
  KnownDevices["Huawei MediaPad M5"],
  KnownDevices["Huawei MediaPad M6"],
  KnownDevices["Lenovo Tab M10"],
  KnownDevices["Lenovo Tab P10"],
  KnownDevices["Sony Xperia Tablet Z"],
  KnownDevices["Sony Xperia Z2 Tablet"],
  KnownDevices["Sony Xperia Z4 Tablet"],
];
